POST http://localhost:8080/api/admin/orders/
Content-Type: application/json
Accept: application/json

{
  "customerId": 1,
  "items": [
    {
      "productId": 1,
      "quantity": 10
    },
    {
      "productId": 2,
      "quantity": 3
    }
  ]
}

###
GET http://localhost:8080/api/admin/orders/
Accept: application/json

###

GET http://localhost:8080/api/admin/orders/1
Accept: application/json

###

POST http://localhost:8080/api/admin/orders/
Content-Type: application/json
Accept: application/json

{
  "customerId": 2,
  "items": [
    {
      "productId": 2,
      "quantity": 5
    },
    {
      "productId": 3,
      "quantity": 1
    }
  ]
}

###


PUT http://localhost:8080/api/admin/orders/2
Content-Type: application/json
Accept: application/json

{
  "deliveryStatus": "DELIVERING"
}

### when id does not exist

DELETE http://localhost:8080/api/admin/orders/20
Accept: application/json

###

GET http://localhost:8080/api/admin/orders/2/items/
Accept: application/json

###

GET http://localhost:8080/api/admin/orders/2/items/3
Accept: application/json

###

POST http://localhost:8080/api/admin/orders/2/items/
Content-Type: application/json
Accept: application/json

{
      "productId": 3,
      "quantity": 1
}

###

PUT http://localhost:8080/api/admin/orders/2/items/4
Content-Type: application/json
Accept: application/json

{
  "productId": 3,
  "quantity": 10
}


###
DELETE http://localhost:8080/api/admin/orders/2/items/4
Accept: application/json