
GET http://localhost:8080/api/admin/products/category/
Accept: application/json

###

GET http://localhost:8080/api/admin/products/category/2
Accept: application/json

###

POST http://localhost:8080/api/admin/products/category/
Content-Type: application/json
Accept: application/json

{
  "name": "Italok",
  "active": false
}

###


PUT http://localhost:8080/api/admin/products/category/3
Content-Type: application/json
Accept: application/json

{
  "name": "Italok2",
  "active": true
}

###

DELETE http://localhost:8080/api/admin/products/category/3
Accept: application/json

###