CREATE TABLE IF NOT EXISTS t_countrycode (
`country_code` VARCHAR(3) NOT NULL,
`country_name` VARCHAR(255) NOT NULL,
`is_active` TINYINT UNSIGNED NOT NULL DEFAULT 0,
PRIMARY KEY (country_code),
CONSTRAINT country_name_01 UNIQUE (country_name),
CONSTRAINT is_active_01 CHECK (is_active=0 or is_active=1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



INSERT INTO t_countrycode (country_code,country_name,is_active)
VALUES
('AFG','Afghanistan',1),
('ALA','Aland Islands',1),
('ALB','Albania',1),
('DZA','Algeria',1),
('ASM','American Samoa',1),
('AND','Andorra',1),
('AGO','Angola',1),
('AIA','Anguilla',1),
('ATA','Antarctica',1),
('ATG','Antigua and Barbuda',1),
('ARG','Argentina',1),
('ARM','Armenia',1),
('ABW','Aruba',1),
('AUS','Australia',1),
('AUT','Austria',1),
('AZE','Azerbaijan',1),
('BHS','Bahamas',1),
('BHR','Bahrain',1),
('BGD','Bangladesh',1),
('BRB','Barbados',1),
('BLR','Belarus',1),
('BEL','Belgium',1),
('BLZ','Belize',1),
('BEN','Benin',1),
('BMU','Bermuda',1),
('BTN','Bhutan',1),
('BOL','Bolivia',1),
('BIH','Bosnia and Herzegovina',1),
('BWA','Botswana',1),
('BVT','Bouvet Island',1),
('BRA','Brazil',1),
('VGB','British Virgin Islands',1),
('IOT','British Indian Ocean Territory',1),
('BRN','Brunei Darussalam',1),
('BGR','Bulgaria',1),
('BFA','Burkina Faso',1),
('BDI','Burundi',1),
('KHM','Cambodia',1),
('CMR','Cameroon',1),
('CAN','Canada',1),
('CPV','Cape Verde',1),
('CYM','Cayman Islands',1),
('CAF','Central African Republic',1),
('TCD','Chad',1),
('CHL','Chile',1),
('CHN','China',1),
('HKG','Hong Kong, SAR China',1),
('MAC','Macao, SAR China',1),
('CXR','Christmas Island',1),
('CCK','Cocos (Keeling) Islands',1),
('COL','Colombia',1),
('COM','Comoros',1),
('COG','Congo (Brazzaville)',1),
('COD','Congo, (Kinshasa)',1),
('COK','Cook Islands',1),
('CRI','Costa Rica',1),
('HRV','Croatia',1),
('CUB','Cuba',1),
('CYP','Cyprus',1),
('CZE','Czech Republic',1),
('DNK','Denmark',1),
('DJI','Djibouti',1),
('DMA','Dominica',1),
('DOM','Dominican Republic',1),
('ECU','Ecuador',1),
('EGY','Egypt',1),
('SLV','El Salvador',1),
('GNQ','Equatorial Guinea',1),
('ERI','Eritrea',1),
('EST','Estonia',1),
('ETH','Ethiopia',1),
('FLK','Falkland Islands (Malvinas)',1),
('FRO','Faroe Islands',1),
('FJI','Fiji',1),
('FIN','Finland',1),
('FRA','France',1),
('GUF','French Guiana',1),
('PYF','French Polynesia',1),
('ATF','French Southern Territories',1),
('GAB','Gabon',1),
('GMB','Gambia',1),
('GEO','Georgia',1),
('DEU','Germany',1),
('GHA','Ghana',1),
('GIB','Gibraltar',1),
('GRC','Greece',1),
('GRL','Greenland',1),
('GRD','Grenada',1),
('GLP','Guadeloupe',1),
('GUM','Guam',1),
('GTM','Guatemala',1),
('GGY','Guernsey',1),
('GIN','Guinea',1),
('GNB','Guinea-Bissau',1),
('GUY','Guyana',1),
('HTI','Haiti',1),
('HMD','Heard and Mcdonald Islands',1),
('VAT','Holy See (Vatican City State)',1),
('HND','Honduras',1),
('HUN','Magyarország',1),
('ISL','Iceland',1),
('IND','India',1),
('IDN','Indonesia',1),
('IRN','Islamic Republic of Iran',1),
('IRQ','Iraq',1),
('IRL','Ireland',1),
('IMN','Isle of Man',1),
('ISR','Israel',1),
('ITA','Italy',1),
('JAM','Jamaica',1),
('JPN','Japan',1),
('JEY','Jersey',1),
('JOR','Jordan',1),
('KAZ','Kazakhstan',1),
('KEN','Kenya',1),
('KIR','Kiribati',1),
('PRK','Korea (North)',1),
('KOR','Korea (South)',1),
('KWT','Kuwait',1),
('KGZ','Kyrgyzstan',1),
('LAO','Lao PDR',1),
('LVA','Latvia',1),
('LBN','Lebanon',1),
('LSO','Lesotho',1),
('LBR','Liberia',1),
('LBY','Libya',1),
('LIE','Liechtenstein',1),
('LTU','Lithuania',1),
('LUX','Luxembourg',1),
('MKD','Macedonia, Republic of',1),
('MDG','Madagascar',1),
('MWI','Malawi',1),
('MYS','Malaysia',1),
('MDV','Maldives',1),
('MLI','Mali',1),
('MLT','Malta',1),
('MHL','Marshall Islands',1),
('MTQ','Martinique',1),
('MRT','Mauritania',1),
('MUS','Mauritius',1),
('MYT','Mayotte',1),
('MEX','Mexico',1),
('FSM','Federated States of Micronesia',1),
('MDA','Moldova',1),
('MCO','Monaco',1),
('MNG','Mongolia',1),
('MNE','Montenegro',1),
('MSR','Montserrat',1),
('MAR','Morocco',1),
('MOZ','Mozambique',1),
('MMR','Myanmar',1),
('NAM','Namibia',1),
('NRU','Nauru',1),
('NPL','Nepal',1),
('NLD','Netherlands',1),
('ANT','Netherlands Antilles',1),
('NCL','New Caledonia',1),
('NZL','New Zealand',1),
('NIC','Nicaragua',1),
('NER','Niger',1),
('NGA','Nigeria',1),
('NIU','Niue',1),
('NFK','Norfolk Island',1),
('MNP','Northern Mariana Islands',1),
('NOR','Norway',1),
('OMN','Oman',1),
('PAK','Pakistan',1),
('PLW','Palau',1),
('PSE','Palestinian Territory',1),
('PAN','Panama',1),
('PNG','Papua New Guinea',1),
('PRY','Paraguay',1),
('PER','Peru',1),
('PHL','Philippines',1),
('PCN','Pitcairn',1),
('POL','Poland',1),
('PRT','Portugal',1),
('PRI','Puerto Rico',1),
('QAT','Qatar',1),
('REU','Réunion',1),
('ROU','Romania',1),
('RUS','Russian Federation',1),
('RWA','Rwanda',1),
('BLM','Saint-Barthélemy',1),
('SHN','Saint Helena',1),
('KNA','Saint Kitts and Nevis',1),
('LCA','Saint Lucia',1),
('MAF','Saint-Martin (French part)',1),
('SPM','Saint Pierre and Miquelon',1),
('VCT','Saint Vincent and Grenadines',1),
('WSM','Samoa',1),
('SMR','San Marino',1),
('STP','Sao Tome and Principe',1),
('SAU','Saudi Arabia',1),
('SEN','Senegal',1),
('SRB','Serbia',1),
('SYC','Seychelles',1),
('SLE','Sierra Leone',1),
('SGP','Singapore',1),
('SVK','Slovakia',1),
('SVN','Slovenia',1),
('SLB','Solomon Islands',1),
('SOM','Somalia',1),
('ZAF','South Africa',1),
('SGS','South Georgia and the South Sandwich Islands',1),
('SSD','South Sudan',1),
('ESP','Spain',1),
('LKA','Sri Lanka',1),
('SDN','Sudan',1),
('SUR','Suriname',1),
('SJM','Svalbard and Jan Mayen Islands',1),
('SWZ','Swaziland',1),
('SWE','Sweden',1),
('CHE','Switzerland',1),
('SYR','Syrian Arab Republic (Syria)',1),
('TWN','Taiwan, Republic of China',1),
('TJK','Tajikistan',1),
('TZA','Tanzania, United Republic of',1),
('THA','Thailand',1),
('TLS','Timor-Leste',1),
('TGO','Togo',1),
('TKL','Tokelau',1),
('TON','Tonga',1),
('TTO','Trinidad and Tobago',1),
('TUN','Tunisia',1),
('TUR','Turkey',1),
('TKM','Turkmenistan',1),
('TCA','Turks and Caicos Islands',1),
('TUV','Tuvalu',1),
('UGA','Uganda',1),
('UKR','Ukraine',1),
('ARE','United Arab Emirates',1),
('GBR','United Kingdom',1),
('USA','United States of America',1),
('UMI','US Minor Outlying Islands',1),
('URY','Uruguay',1),
('UZB','Uzbekistan',1),
('VUT','Vanuatu',1),
('VEN','Venezuela (Bolivarian Republic)',1),
('VNM','Viet Nam',1),
('VIR','Virgin Islands',1),
('WLF','Wallis and Futuna Islands',1),
('ESH','Western Sahara',1),
('YEM','Yemen',1),
('ZMB','Zambia',1),
('ZWE','Zimbabwe',1);